<?php
namespace App\Http\Common;

class settingcommon {
	public static function getDbFieldsforProcess() {
		return array('ams_master_expenses_main' => array('labels' =>
									array('heading' => trans('messages.lbl_main_category'),
									 	'field1lbl' => trans('messages.lbl_main_category')),
										'selectfields' => array('id',
																'category',
																'createdDateTime',
																'delFlg',
																'orderId'),
										'displayfields' => array('id',
																'category',
																'createdDateTime',
																'delFlg',
																'orderId'),
										'insertfields' => array('category',
																'delFlg',
																'createdDateTime',
																'updatedDateTime',
																'createdBy',
																'updatedBy',
																'orderId'),
										'updatefields' => array('category',
															  'updatedDateTime',
															  'UpdatedBy'),
										'usenotusefields' => array('delFlg'),
										'commitfields' => array('orderId')),

					'ams_master_expenses_sub' => array('labels' =>
										array('heading' => trans('messages.lbl_sub_category'),
											'field1lbl' => trans('messages.lbl_main_category'),
											'field2lbl' => trans('messages.lbl_sub_category')),
											'selectfields' => array('id',
																	'category',
																	'categoryId',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'displayfields' => array('id',
																	'category',
																	'categoryId',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'insertfields' => array('category',
																	'categoryId',
																	'delFlg',
																	'createdDateTime',
																	'updatedDateTime',
																	'createdBy',
																	'updatedBy',
																	'orderId'),
											'updatefields' => array('category',
																	'categoryId',
																	'updatedBy',
																	'updatedDateTime'),
											'usenotusefields' => array('delFlg'),
											'commitfields' => array('orderId'),
											'selectboxfields' => array('id','category')),

					'ams_master_buildingname' => array('labels' =>
									array('heading' => trans('messages.lbl_building_name'),
									 	'field1lbl' => trans('messages.lbl_building_name')),
										'selectfields' => array('id',
																'buildingName',
																'createdDateTime',
																'delFlg',
																'orderId'),
										'displayfields' => array('id',
																'buildingName',
																'createdDateTime',
																'delFlg',
																'orderId'),
										'insertfields' => array('buildingName',
																'delFlg',
																'createdDateTime',
																'updatedDateTime',
																'createdBy',
																'updatedBy',
																'orderId'),
										'updatefields' => array('buildingName',
															  'updatedDateTime',
															  'UpdatedBy'),
										'usenotusefields' => array('delFlg'),
										'commitfields' => array('orderId')),

					'ams_master_houseimg_main' => array('labels' =>
									array('heading' => trans('messages.lbl_houseimgmain'),
									 	'field1lbl' => trans('messages.lbl_main_category')),
										'selectfields' => array('id',
																'imageName',
																'createdDateTime',
																'delFlg',
																'orderId'),
										'displayfields' => array('id',
																'imageName',
																'createdDateTime',
																'delFlg',
																'orderId'),
										'insertfields' => array('imageName',
																'delFlg',
																'createdDateTime',
																'updatedDateTime',
																'createdBy',
																'updatedBy',
																'orderId'),
										'updatefields' => array('imageName',
															  'updatedDateTime',
															  'UpdatedBy'),
										'usenotusefields' => array('delFlg'),
										'commitfields' => array('orderId')),

					'ams_master_houseimg_sub' => array('labels' =>
										array('heading' => trans('messages.lbl_houseimgsub'),
											'field1lbl' => trans('messages.lbl_main_category'),
											'field2lbl' => trans('messages.lbl_sub_category')),
											'selectfields' => array('id',
																	'imageName',
																	'imageId',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'displayfields' => array('id',
																	'imageName',
																	'imageId',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'insertfields' => array('imageName',
																	'imageId',
																	'delFlg',
																	'createdDateTime',
																	'updatedDateTime',
																	'createdBy',
																	'updatedBy',
																	'orderId'),
											'updatefields' => array('imageName',
																	'imageId',
																	'updatedBy',
																	'updatedDateTime'),
											'usenotusefields' => array('delFlg'),
											'commitfields' => array('orderId'),
											'selectboxfields' => array('id','imageName')),
					
					'ams_family_master' => array('labels'=>
										array('heading' => trans('messages.lbl_familymember'),
											'field1lbl' => trans('messages.lbl_familymember')),
											'selectfields' => array('id',
																	'familyName',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'displayfields' => array('id',
																	'familyName',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'insertfields' => array('familyName',
																	'delFlg',
																	'createdDateTime',
																	'updatedDateTime',
																	'createdBy',
																	'updatedBy',
																	'orderId'),
											'updatefields' => array('familyName',
																	'updatedDateTime',
																	'UpdatedBy'),
											'usenotusefields' => array('delFlg'),
											'commitfields' => array('orderId')),

					'ams_bankname_master' => array('labels'=>
										array('heading' => trans('messages.lbl_bankdetails'),
											'field1lbl' => trans('messages.lbl_bank_name'),
											'field2lbl' => trans('messages.lbl_bank_nickname')),
											'selectfields' => array('id',
																	'bankName',
																	'nickName',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'displayfields' => array('id',
																	'bankName',
																	'nickName',
																	'createdDateTime',
																	'delFlg',
																	'orderId'),
											'insertfields' => array('bankName',
																	'nickName',
																	'delFlg',
																	'createdDateTime',
																	'updatedDateTime',
																	'createdBy',
																	'updatedBy',
																	'orderId'),
											'updatefields' => array('bankName',
																	'nickName',
																	'updatedDateTime',
																	'updatedBy'),
											'usenotusefields' => array('delFlg'),
											'commitfields'=> array('orderId')),

				'ams_master_assetstypes' => array('labels' =>
											array('heading' =>trans('messages.lbl_assetstypes'),
												'field1lbl' =>trans('messages.lbl_assetstypes')),
												'selectfields' => array('id',
																		'assetsTypes',
																		'createdDateTime',
																		'delFlg',
																		'orderId'),
												'displayfields' => array('id',
																		'assetsTypes',
																		'createdDateTime',
																		'delFlg',
																		'orderId'),
												'insertfields' => array('assetsTypes',
																		'delFlg',
																		'createdDateTime',
																		'updatedDateTime',
																		'createdBy',
																		'updatedBy',
																		'orderId'),
												'updatefields' => array('assetsTypes',
																		'updatedDateTime',
																		'UpdatedBy'),
												'usenotusefields' => array('delFlg'),
												'commitfields' => array('orderId')),
		);
	}
}
